apiVersion: v1
kind: Service
metadata:
  name: {{ include "trivy.fullname" . }}
  labels:
    {{- include "trivy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "trivy.selectorLabels" . | nindent 4 }}
